version: "3.9"
services:
  app:
    image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION} 
    restart: always                               
    ports:                                         
      - "8080"                                     
    container_name: ${APP_NAME}_app                
    environment:
      WS_HOST: ws://${HOST_DOMAIN}
      WS_PORT: 80
      VIRTUAL_HOST: ${HOST_DOMAIN}
      VIRTUAL_PORT: 8080 # New default ASP.NET port -> https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/aspnet-port
      LETSENCRYPT_HOST: ${HOST_DOMAIN}           
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LC_ALL: "en_US.UTF-8"
      LANG: "en_US.UTF-8"
    volumes:
      - app-mydb:/app/App_Data  

  ${APP_NAME}-migration:
    image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION}
    restart: "no"
    profiles:
      - migration
    command: --AppTasks=migrate
    volumes:
      - ${APP_NAME}-mydb:/app/App_Data

volumes:
  ${APP_NAME}-mydb:
